// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductsOrdersAPI.Data;

#nullable disable

namespace ProductsOrdersAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241010173717_CreatingProductTableAndSeeders")]
    partial class CreatingProductTableAndSeeders
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ProductsOrdersAPI.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Productos relacionados con tecnología y dispositivos electrónicos.",
                            Name = "Electrónica"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Artículos para la casa, desde muebles hasta decoración.",
                            Name = "Hogar"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Ropa y accesorios de última tendencia.",
                            Name = "Moda"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Equipamiento y ropa para diversas actividades deportivas.",
                            Name = "Deportes"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Productos de cuidado personal y bienestar.",
                            Name = "Salud y Belleza"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Juguetes y juegos para niños de todas las edades.",
                            Name = "Juguetes"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Accesorios y piezas para vehículos.",
                            Name = "Automotriz"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Comida y bebidas de diversas culturas.",
                            Name = "Alimentos y Bebidas"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Literatura y libros de texto en diferentes géneros.",
                            Name = "Libros"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Herramientas y productos para el cuidado del jardín.",
                            Name = "Jardinería"
                        });
                });

            modelBuilder.Entity("ProductsOrdersAPI.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<double>("Price")
                        .HasColumnType("double")
                        .HasColumnName("price");

                    b.Property<int>("Stock")
                        .HasColumnType("int")
                        .HasColumnName("stock");

                    b.HasKey("Id");

                    b.ToTable("products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "teléfono inteligente con pantalla táctil.",
                            Name = "smartphone",
                            Price = 299.99000000000001,
                            Stock = 50
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "portátil con alto rendimiento para trabajo y juego.",
                            Name = "laptop",
                            Price = 899.99000000000001,
                            Stock = 30
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "televisor con resolución 4k para una experiencia visual impresionante.",
                            Name = "televisor 4k",
                            Price = 499.99000000000001,
                            Stock = 20
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "sofá de tres plazas, cómodo y elegante.",
                            Name = "sofá",
                            Price = 499.99000000000001,
                            Stock = 15
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Description = "mesa de madera para 6 personas.",
                            Name = "mesa de comedor",
                            Price = 299.99000000000001,
                            Stock = 10
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Description = "lámpara de mesa moderna con luz led.",
                            Name = "lámpara de mesa",
                            Price = 49.990000000000002,
                            Stock = 40
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Description = "bicicleta diseñada para senderos y montaña.",
                            Name = "bicicleta de montaña",
                            Price = 599.99000000000001,
                            Stock = 25
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Description = "calzado deportivo ligero y cómodo.",
                            Name = "zapatillas de correr",
                            Price = 89.989999999999995,
                            Stock = 60
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Description = "balón oficial de fútbol para jugar en el campo.",
                            Name = "balón de fútbol",
                            Price = 29.989999999999998,
                            Stock = 100
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 4,
                            Description = "crema para el cuidado de la piel, ideal para todo tipo de piel.",
                            Name = "crema hidratante",
                            Price = 19.989999999999998,
                            Stock = 80
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 4,
                            Description = "champú para un cabello sano y brillante.",
                            Name = "champú",
                            Price = 15.99,
                            Stock = 90
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 5,
                            Description = "juguete para construir diferentes formas y estructuras.",
                            Name = "juguete de construcción",
                            Price = 34.990000000000002,
                            Stock = 50
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 5,
                            Description = "muñeca hecha a mano, suave y amigable.",
                            Name = "muñeca de trapo",
                            Price = 25.989999999999998,
                            Stock = 45
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 5,
                            Description = "auto a control remoto, ideal para niños.",
                            Name = "auto de control remoto",
                            Price = 49.990000000000002,
                            Stock = 35
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 6,
                            Description = "kit completo para reparación y mantenimiento del hogar.",
                            Name = "kit de herramientas",
                            Price = 79.989999999999995,
                            Stock = 20
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 6,
                            Description = "silla ergonómica para oficina, ajustable.",
                            Name = "silla de oficina",
                            Price = 129.99000000000001,
                            Stock = 10
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 6,
                            Description = "funda para sillón, fácil de lavar.",
                            Name = "funda de sillón",
                            Price = 39.990000000000002,
                            Stock = 60
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 7,
                            Description = "cerveza elaborada de manera artesanal.",
                            Name = "cerveza artesanal",
                            Price = 2.9900000000000002,
                            Stock = 200
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 7,
                            Description = "café de alta calidad, 100% orgánico.",
                            Name = "café orgánico",
                            Price = 12.99,
                            Stock = 150
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 7,
                            Description = "chocolate de alta calidad con sabores exóticos.",
                            Name = "chocolate gourmet",
                            Price = 4.9900000000000002,
                            Stock = 300
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 8,
                            Description = "una obra literaria clásica de la literatura.",
                            Name = "novela clásica",
                            Price = 14.99,
                            Stock = 80
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 8,
                            Description = "recetario con deliciosas recetas.",
                            Name = "libro de cocina",
                            Price = 19.989999999999998,
                            Stock = 60
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 8,
                            Description = "guía completa para visitar diferentes destinos.",
                            Name = "guía de viaje",
                            Price = 24.989999999999998,
                            Stock = 40
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 9,
                            Description = "maceta decorativa para plantas.",
                            Name = "maceta de cerámica",
                            Price = 9.9900000000000002,
                            Stock = 100
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 9,
                            Description = "tijeras para podar y cuidar plantas.",
                            Name = "tijeras de jardín",
                            Price = 19.989999999999998,
                            Stock = 80
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 9,
                            Description = "guantes resistentes para trabajar en el jardín.",
                            Name = "guantes de jardinería",
                            Price = 14.99,
                            Stock = 90
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 10,
                            Description = "cuchillo de chef de alta calidad.",
                            Name = "cuchillo de cocina",
                            Price = 39.990000000000002,
                            Stock = 40
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 10,
                            Description = "sartén de alta calidad para cocinar sin que se pegue.",
                            Name = "sartén antiadherente",
                            Price = 29.989999999999998,
                            Stock = 50
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 10,
                            Description = "cuchara ecológica de madera.",
                            Name = "cuchara de madera",
                            Price = 4.9900000000000002,
                            Stock = 100
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 10,
                            Description = "batidora compacta y fácil de usar.",
                            Name = "batidora de mano",
                            Price = 49.990000000000002,
                            Stock = 30
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
